# Generated by Django 4.1.4 on 2022-12-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("response", models.TextField()),
                ("datetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
